version: '3.0'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      LOG_LEVEL: INFO
    volumes:
      - /home/mf16/work/bbmri/sandbox/muni-sc/:/muni-sc/
    command: bash -c "python main.py
                              -r /muni-sc/pseudonymized_runs/
                              -o /muni-sc/organized_runs/
                              -p /muni-sc/Patients/
                              -l /muni-sc/organized_runs/logs/organizer"
