version: '3.0'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      LOG_LEVEL: INFO
    volumes:
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/muni-ss/OrganisedRuns/:/OrganisedRuns
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/muni-ss/PSEUDONYMIZED/:/PseudonymizedRuns
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/muni-ss/Patients/:/Patients
    command: bash -c "python main.py
                              -r /PseudonymizedRuns/
                              -o /OrganisedRuns/
                              -p /Patients/"
