version: '3.0'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/houfek/Work/MMCI/sequencing_pipeline/data-catalogue-playground/muni-sc/PseudonymizedRuns:/PseudonymizedRuns
      - /home/houfek/Work/MMCI/sequencing_pipeline/data-catalogue-playground/muni-sc/NextSeqTemp/:/NextSeqTemp
      - /home/houfek/Work/MMCI/sequencing_pipeline/data-catalogue-playground/muni-sc/OrganisedRuns/:/OrganisedRuns
      - /home/houfek/Work/MMCI/sequencing_pipeline/data-catalogue-playground/muni-sc/Patients/:/Patients
    command: bash -c "python main.py
                              -r /PseudonymizedRuns/
                              -n /NextSeqTemp/
                              -o /OrganisedRuns/
                              -p /Patients/"