apiVersion: batch/v1
kind: CronJob
metadata:
  name: organise-sequencing
spec:
  schedule: "0 22 * * 3,6"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1005
            runAsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
          - name: organise-sequencing
            image: tomashoufek/data-catalogue-organiser:1.2.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            env:
              - name: CATALOG-LOGIN
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: username
              - name: CATALOG-PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: password
              - name: HTTPS_PROXY
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: httpsproxy
            command: ["python", "/scripts/pipeline.py", "-r", "/data/PSEUDONYMIZED-MiSEQ", "-o", "/data/OrganisedRuns/", "-p", "/data/Patients/", "-w",  /wsi/, "-d", "/data/Libraries/"]
            volumeMounts:
            - name: storage-catalogue-volume
              mountPath: /data/
              subPath: MiSEQ
            - name: data-wsi-volume
              mountPath: /wsi/
              subPath: tiff
          restartPolicy: "Never"
          volumes:
          - name: storage-catalogue-volume
            persistentVolumeClaim:
              claimName: pvc-storage-catalogue-secret
          - name: data-wsi-volume
            persistentVolumeClaim:
              claimName: pvc-osd-secret