apiVersion: batch/v1
kind: CronJob
metadata:
  name: organise-sequencing
spec:
  schedule: "0 22 * * 2,4,6"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1005
            runAsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
          - name: organise-sequencing
            image: tomashoufek/data-catalogue-organiser:1.3.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            command: ["python", "main.py", "-r", "/data/PSEUDONYMIZED", "-o", "/data/OrganisedRuns/", "-p", "/data/Patients/"]
            volumeMounts:
            - name: storage-catalogue-volume
              mountPath: /data/
          restartPolicy: "Never"
          volumes:
          - name: storage-catalogue-volume
            persistentVolumeClaim:
              claimName: pvc-storage-catalogue-secret
